export const SET_MAPPED_ENTRY_DATA = "SET_MAPPED_ENTRY_DATA";

export const SET_ALL_ENTRIES = "SET_ALL_ENTRIES";

export const SET_ENTRY_STATISTICS = "SET_ENTRIES_STATISTICS";

export const SET_RECENT_ENTRIES = "SET_RECENT_ENTRIES";
