export const SET_CALENDAR_ENTRIES = "SET_CALENDAR_ENTRIES";

export const SET_ALL_ENTRIES = "SET_ALL_ENTRIES";

export const SET_WEEK_ENTRIES = "SET_WEEK_ENTRIES";
export const SET_MONTH_ENTRIES = "SET_MONTH_ENTRIES";
export const SET_THREE_MONTH_ENTRIES = "SET_THREE_MONTH_ENTRIES";
export const SET_SIX_MOTH_ENTRIES = "SET_SIX_MONTH_ENTRIES";
export const SET_YEAR_ENTRIES = "SET_YEAR_ENTRIES";

export const SET_RECENT_ENTRIES = "SET_RECENT_ENTRIES";
