CalendarTable: 
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CalendarTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userID
        AttributeType: S
    KeySchema: 
      - AttributeName: userID
        KeyType: HASH