# NOTE: update this with your service name
service: LeetLogger

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom: 
  bundle: 
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2 
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    questionTable: leetlogger-questions
    entryTable: leetlogger-entries 
    s3BucketName: leetlogger-notes-and-solutions

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dyanmodb:DeleteItem
        - dynamodb:Query
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: 
        arn:aws:dynamodb:us-west-2:*:*
    - Effect: "Allow"
      Action: 
        - s3:*
      Resource: 
        arn:aws:s3:::*
    
functions:
  addEntry:
    handler: src/entries/addEntry.main
    events:
      - http:
          path: entries
          method: post
          cors: true

  updateEntry: 
    handler: src/entries/updateEntry.main
    events:
      - http:
          path: entries/{entryId}
          method: put 
          cors: true
  
  getEntry: 
    handler: src/entries/getEntry.main
    events:
      - http: 
          path: entries/{entryId}
          method: get 
          cors: true

  deleteEntry: 
    handler: src/entries/deleteEntry.main
    events:
      - http:
          path: entries/{entryId}
          method: delete
          cors: true
          
  listEntriesAll:
    handler: src/entries/listEntriesAll.main
    events:
      - http:
          path: entries/list
          method: get 
          cors: true 
  
  listEntriesBySubmittedAt:
      handler: src/entries/listEntriesBySubmittedAt.main
      events: 
        - http:
            path: entries/list/entriesInTwoDays
            method: get 
            cors: true 
  
  listEntriesByType:
      handler: src/entries/listEntriesByType.main
      events: 
        - http:
            path: entries/list/type/{type}
            method: get 
            cors: true